//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public int movieId { get; set; }
        public int userid { get; set; }
        public int tickets { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual movies movies { get; set; }
        public virtual user user { internal get; set; }
    }
}
